### PR TITLE
RL-update-v2.3.0

### PR DESCRIPTION
**Pull request by ivukovicRL**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by ivukovicRL** [comment]
We have GUID error:
image

Thing is, we want to rename this app because we  support more actions now. Previous name was given after only one of these actions (APIs) and thus woud be incorrect now.

**Comment by ivukovicRL** [comment]
Can we get an explanation on this error:
image
Thanks

**Comment by arathore-crest** [comment]
> We have GUID error: image
> 
> Thing is, we want to rename this app because we support more actions now. Previous name was given after only one of these actions (APIs) and thus woud be incorrect now.

I'll update the App Name and GUID mapping

**Comment by arathore-crest** [comment]
> Can we get an explanation on this error: image Thanks

The action names used are new/unknown as they do not correspond to the existing action names we have in Phantom. We'll update the action mapping accordingly to incorporate these.

**Comment by ivukovicRL** [comment]
Hi @arathore-crest, we would like to continue with the release, if there are any issues please let us know.

**Comment by arathore-crest** [comment]
> Hi @arathore-crest, we would like to continue with the release, if there are any issues please let us know.

Sure, we'll proceed with the developer checklist and sanity testing for the app.

**Comment by haritas-crest** [comment]
Hi @ivukovicRL, can you please provide me the access to the repo(reversinglabs:rl-update-v2.3.0) ?

**Comment by haritas-crest** [comment]
Hi @ivukovicRL,
We observed that you have updated the license from "Copyright (c) ReversingLabs Inc 2016-2018" to "Copyright (c) 2016-2022 Splunk Inc.". Is there any specific reason to update this?

**Comment by ivukovicRL** [comment]
> We observed that you have updated the license from "Copyright (c) ReversingLabs Inc 2016-2018" to "Copyright (c) 2016-2022 Splunk Inc.". Is there any specific reason to update this?

Hi @haritas-crest  it was an old license and we have seen that the other partners also use your license so we decided to go with that.

**Comment by mjiyani-crest** [comment]
> > We observed that you have updated the license from "Copyright (c) ReversingLabs Inc 2016-2018" to "Copyright (c) 2016-2022 Splunk Inc.". Is there any specific reason to update this?
> 
> Hi @haritas-crest it was an old license and we have seen that the other partners also use your license so we decided to go with that.

Hey @ivukovicRL , I guess you have referred to the Splunk-supported apps which are using the Splunk license. But this app is a developer-supported app, so the license should be third-party and not the Splunk license.

Hence, either we can use "Copyright (c) ReversingLabs Inc 2016-2022" or if there is any new license of third-party. Please suggest if there is any new license otherwise we are good to go with the ReversingLabs license.

Please let us know in case of any queries.

Thanks
Mit

**Comment by ivukovicRL** [comment]
Hi @mjiyani-crest is it ok with you that we put the MIT license here? 

Also, we already have our [reversinglabs-tiscale](https://github.com/splunk-soar-connectors/reversinglabs-tiscale)  app published recently and it has your license in it. I suppose we should update that one?

**Comment by mjiyani-crest** [comment]
@ivukovicRL thanks for letting us know for [reversinglabs-tiscale](https://github.com/splunk-soar-connectors/reversinglabs-tiscale), we will update that at our end. Regarding the license, it should be Apache 2.0 which we maintains in all the files as header text.

Regarding copyrights, it should be of Reversings Labs as the license key is meant to keep copyright details in JSON for now.

Please let us know in case of queries.
Thanks,
Mit.

**Comment by ivukovicRL** [comment]
Hi @mjiyani-crest we are ok with the Apache license.

**Comment by haritas-crest** [comment]
Hi @ivukovicRL,
We have made some changes to the app as per our standard practice.
Can you please verify and test them in your environment?
Also, we have removed the unused wheel files.

Please let us know in case of any queries.

**Review by joshquerinphantom — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
